Update status of xfce4-terminal
smasher164/arewesixelyet pull request #3
Opened 2022-08-09 01:19 UTC by adsr

2022-08-09 03:20 UTC, smasher164 requested changes
Thanks for submitting this. Please run
```
hugo -D
```
to update the generated html.

2022-08-10 01:00 UTC, adsr commented
I'm probably missing something.

```
$ git show | head -n1
commit d78d2ba14563ff915c7ea34b1b7fb8525f57710f
$ hugo -D --debug
Start building sites … 
hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66 linux/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio
INFO 2022/08/09 20:57:40 syncing static files to /
DEBUG 2022/08/09 20:57:40 Render page  to "/index.html"
WARN 2022/08/09 20:57:40 found no layout file for "HTML" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2022/08/09 20:57:40 found no layout file for "HTML" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
DEBUG 2022/08/09 20:57:40 Render XML for "sitemap" to "/sitemap.xml"
DEBUG 2022/08/09 20:57:40 Render page  to "/index.xml"
DEBUG 2022/08/09 20:57:40 Render page Categories to "/categories/index.xml"
DEBUG 2022/08/09 20:57:40 Render page Tags to "/tags/index.xml"

                   | EN  
-------------------+-----
  Pages            |  3  
  Paginator pages  |  0  
  Non-page files   |  0  
  Static files     |  0  
  Processed images |  0  
  Aliases          |  0  
  Sitemaps         |  1  
  Cleaned          |  0  

Total in 15 ms
$ git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
$ 
```

2022-08-11 00:05 UTC, smasher164 commented
Yeah it's weird that it's not being tracked by `git status`. I'll go ahead and merged, and run `hugo -D` separately.

2022-08-11 00:05 UTC, smasher164 approved these changes

2022-08-11 00:05 UTC, merged